---
- hosts: webserver
  become: true
  tasks:
    - name: install  web components
      apt: name={{item}} status=present update_cache=yes
      with_items:
        - apache2
        - libapache2-mod-wsgi
        - python-pip
        - python-virtualenv

        # used with_items(which is jinja syntax) allows us to use variables.