---
- hosts: target
  become: true
  tasks:
  - name: installing nginx
    apt:
     name: nginx
     state: present		
     update_cache: true
  - name: starting nginx
    service:
       name: nginx
       state: started
       enabled: true
